import Head from "next/head";
import Image from "next/image";

import styles from "@/components/home/styles/Home.module.scss";
import Header from "@/components/header/headre";
import Main from "@/components/main/main";
import Footer from "@/components/footer/footer";
import OneSection from "@/components/oneSection/oneSection";
import TweSection from "@/components/tweSection/tweSection";

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Header />
        <main>
          <Main />
          <OneSection />
          <TweSection />
        </main>
        <Footer />
      </div>
    </>
  );
}

export default Home;
